### ISSUE TITLE
[Bug]: Calling a toast shows 2 toast, one with the expected values and one empty

### ISSUE THREAD

**Issue by Ryuuji159** [tasteui/tasteui#271] opened 2024-01-29 18:26 UTC
### What Happened

Calling a toast is generating 2 toasts, one with the expected values and one empty (as the title says) 
This generates a lot of errors on the console and while the first one disapears normaly, the second keeps looping forever.

![image](https://github.com/tallstackui/tallstackui/assets/17039188/77d677f0-d88d-412f-ba02-54c64d822295)

![image](https://github.com/tallstackui/tallstackui/assets/17039188/b3bc227f-fa4c-4ec8-8995-bb12eba0f89e)

![image](https://github.com/tallstackui/tallstackui/assets/17039188/3597e706-7fd6-4e14-9863-10dc0e68cf1f)

### How to Reproduce

Im calling the toast shown like this `$this->toast()->success('Tipo de compromiso eliminado correctamente')->send();` inside a livewire component that's using the `Interactions` trait with `<x-toast/>`  defined on the same component, as it isn't on every page.

I have also confirmed that I dont have repeated toasts on the page.

### Laravel Version

10.35.0

### Livewire Version

3.2.6

### TallStackUI Version

1.13.1

### PHP Version

^8.1

### Operation System

Linux

**Comment by devajmeireles** [comment] 2024-01-29 18:33
I was unable to reproduce this. 

A very good way for my analysis would be to access the code base and check the reason for the problem.

---

I noticed that you are out of date with Laravel and Livewire. Try to run these three commands at the root of the project:

```shell
composer update && npm run build && php artisan optimize:clear
```

Check if the issue still happens after executing the above command.

**Comment by Ryuuji159** [comment] 2024-01-29 18:48
It still happens after the update. but I decided to move the declaration from the files that uses it to the base layout and now it works.
Maybe it was something that happened by appearing and disapearing from the page?

**Comment by devajmeireles** [comment] 2024-01-29 18:50
> It still happens after the update. but I decided to move the declaration from the files that uses it to the base layout and now it works. Maybe it was something that happened by appearing and disapearing from the page?

I really do not know. The only way I could answer for sure would be if I looked at the code base.

I will close the issue. If this happens again, please provide a copy of the repository.

With this contribution, we will ensure that the problem (if it is a problem) is corrected. Thank you very much so far. 👍🏻

**Closed as completed by devajmeireles** 2024-01-29 18:50 UTC
Labels: bugfix
