### ISSUE TITLE
[Bug]: Error in component date when using Form

### ISSUE THREAD

**Issue by leofranca47** [tasteui/tasteui#701] opened 2024-10-05 10:01 UTC
### What Happened

When I use <x-date format="DD/MM/YYYY" wire:model="form.data"/> and add variables to the form, if I use wire:model.live and update a variable in the form, the date format changes.

### Component

Alert

### How to Reproduce

teste.blade.php

```
<div class="w-60 flex flex-col space-y-4">
    <x-date format="DD/MM/YYYY" wire:model="form.data"/>
    <x-input wire:model.live.debounce.500ms="form.cep"/>
    <x-input wire:model="form.resultado"/>
</div>
```

Teste.php

```
<?php

namespace App\Livewire;

use Livewire\Component;

class Teste extends Component
{
    public \App\Livewire\Forms\teste $form;

    public function updatedFormCep(): void
    {
        $this->form->resultado = $this->form->cep;
    }

    public function render()
    {
        return view('livewire.teste');
    }
}
```

teste.php (Form)

```
<?php

namespace App\Livewire\Forms;

use Livewire\Attributes\Validate;
use Livewire\Form;

class teste extends Form
{
    public string $data = '2024-01-01';
    public string $cep = '';
    public string $resultado = '';
}
```

![image](https://github.com/user-attachments/assets/282209f5-848b-472a-a4b9-3d7d663122f8)

![image](https://github.com/user-attachments/assets/53d455f7-7e25-4712-88dc-cf01dec3e578)

### Public Repository

https://github.com/leofranca47/problema-date-tsui

### Laravel Version

11.26.0

### Livewire Version

3.5

### TallStackUI Version

1.35

### PHP Version

8.3.12

### Operation System

Linux

**Comment by devajmeireles** [comment] 2024-10-16 13:42
While I took a brief break from developing TallStackUI to take care of my move to a new house, I'll look at it today!

**Comment by devajmeireles** [comment] 2024-10-16 15:19
I was able to find the reason. It's something related to Livewire from objects. The issue only happens when you're using form objects. I'll check it out what is the way to fix that.

**Comment by leofranca47** [comment] 2024-10-16 16:17
I love TSUI, Thank's

**Comment by devajmeireles** [comment] 2024-10-16 16:47
@leofranca47 , 

After some deep debugging, I can confirm that TSUI does not have any issues related to Livewire form objects. The issue you are facing is specific to your Livewire component, precisely here:

```php
public function updatedFormCep(): void
{
    $this->form->resultado = $this->form->cep;
}
```

If you comment on this piece of code, you'll see all works fine:

![CleanShot 2024-10-16 at 13 45 42](https://github.com/user-attachments/assets/85282672-33f7-4075-9182-f3bdf359a8f6)

I'll close this as completed since there is nothing we need to do.

**Closed as completed by devajmeireles** 2024-10-16 16:47 UTC

**Comment by leofranca47** [comment] 2024-10-17 09:26
If update some info this form, this input date lost format
